# Generated by Django 6.0.7 on 2026-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='link',
            field=models.URLField(blank=True, help_text='Посилання на сайт або відео YouTube — відкриється прямо на сторінці.', verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='materials/%Y/%m/', verbose_name='Файл'),
        ),
    ]
