# Generated by Django 6.0.7 on 2026-08-15 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва проекту')),
                ('description', models.TextField(verbose_name='Опис проекту')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Превью / Скриншот')),
                ('link', models.URLField(blank=True, verbose_name='Ссилка на проект  або GitHub')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавлення')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
